"""Column metadata for the Meteostat daily weather dataset."""

METEOSTAT_COLUMNS = {
    "YEAR": {"name": "year", "feature_type": "datetime"},
    "MONTH": {"name": "month", "feature_type": "datetime"},
    "DAY": {"name": "day", "feature_type": "datetime"},
    "TEMP": {"name": "temp", "feature_type": "numeric"},
    "TEMP_SOURCE": {"name": "temp_source", "feature_type": "categorical"},
    "TMIN": {"name": "tmin", "feature_type": "numeric"},
    "TMIN_SOURCE": {"name": "tmin_source", "feature_type": "categorical"},
    "TMAX": {"name": "tmax", "feature_type": "numeric"},
    "TMAX_SOURCE": {"name": "tmax_source", "feature_type": "categorical"},
    "RHUM": {"name": "rhum", "feature_type": "numeric"},
    "RHUM_SOURCE": {"name": "rhum_source", "feature_type": "categorical"},
    "PRCP": {"name": "prcp", "feature_type": "numeric"},
    "PRCP_SOURCE": {"name": "prcp_source", "feature_type": "categorical"},
    "SNWD": {"name": "snwd", "feature_type": "numeric"},
    "SNWD_SOURCE": {"name": "snwd_source", "feature_type": "categorical"},
    "WSPD": {"name": "wspd", "feature_type": "numeric"},
    "WSPD_SOURCE": {"name": "wspd_source", "feature_type": "categorical"},
    "WPGT": {"name": "wpgt", "feature_type": "numeric"},
    "WPGT_SOURCE": {"name": "wpgt_source", "feature_type": "categorical"},
    "PRES": {"name": "pres", "feature_type": "numeric"},
    "PRES_SOURCE": {"name": "pres_source", "feature_type": "categorical"},
    "TSUN": {"name": "tsun", "feature_type": "numeric"},
    "TSUN_SOURCE": {"name": "tsun_source", "feature_type": "categorical"},
    "CLDC": {"name": "cldc", "feature_type": "numeric"},
    "CLDC_SOURCE": {"name": "cldc_source", "feature_type": "categorical"},
}
